### ISSUE TITLE
UED problem: view articles when writing comments

### ISSUE THREAD

**Issue by askender** [thematters/matters-web#1434] opened 2020-05-04 09:16 UTC
When I am writing comment on an article, it is hard to view the article in the meanwhile.
It is important because I wish to review on many viewpoints of the article.
Thansk.

**Comment by devformatters** [comment] 2022-07-28 04:52
Thank you for your suggestion.

We've release some design updates, and the issue is a bit outdated. I'll close this issue. Feel free to file a new issue if you have more ideas.

**Closed by devformatters** 2022-07-28 04:52 UTC
Labels: enhancement
