### ISSUE TITLE
[Web] Fix "Back to discover" Button spacing

### ISSUE THREAD

**Issue by Jasmine-liang** [thematters/matters-web#2567] opened 2022-07-02 06:25 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/63624438/176989330-4e9af43e-742f-4a33-b8f1-b6f9e8de87a2.png)

**To Reproduce**
Any [error page](https://matters.news/lol)

**Desktop (please complete the following information):**
 - OS: [Manjaro Linux]
 - Browser [Chrome]
 - Version [102.0.5005.61]

**Comment by xavier-kong** [comment] 2022-07-05 06:25
Hi may I know if the issue is open? I am interested in working on it.

**Comment by xavier-kong** [comment] 2022-07-05 13:43
@robertu7 could I get this issue assigned to me?

**Comment by robertu7** [comment] 2022-07-05 13:44
@xavier-kong assigned.

**Closed** 2022-07-05 14:37 UTC
Labels: bug, good first issue
